### PR TITLE
Add myself to site

### PR DESCRIPTION
**Pull request by Brain-0ut**
Maybe I finished the homework of git ))

### CODE REVIEW

**Comment by KseniiaPelykh** [comment]
Well done! some smaller changes to make it work 👍

**Comment by Brain-0ut** [comment]
I moved the picture to the right place.
Any other issues present?

**Comment by KseniiaPelykh** [comment]
> I moved the picture to the right place. Any other issues present?

Thanks! one last thing - there is a problem with 0 and O character in the href and mapping reference. `router.get('/BrainOut', (req, res, next) => {` and `<a href="students/brain0ut">`. I think you also need to use the same extension of the picture in your ref that is `jpg` and not `jpeg`

**Comment by Brain-0ut** [comment]
I think all bugs have been fixed.

**Comment by KseniiaPelykh** [comment]
Cool!

**Pull request merged**
